---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
    # Something with systemd
    - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[pi-dns::default]
