name 'pi-dns'
maintainer 'Aaron Kalair'
maintainer_email 'aaronkalair@gmail.com'
license 'Apache'
description 'Installs/Configures pihole with cloudflared'
long_description 'Installs/Configures pihole with cloudflared'
version '0.3.0'
chef_version '>= 14.0'

depends 'docker'
depends 'poise-python'
